### PR TITLE
remove `replace_code` function

### PR DESCRIPTION
**Pull request by chlebowa**
Rolls back #160

### CODE REVIEW

**Review by donyunardi — APPROVED** [review]
LGTM!

**Review by gogonzo — CHANGES_REQUESTED** [review]
Please wait. I have not fixed connectors to use wrappers

**Comment by chlebowa** [comment]
> Please wait. I have not fixed connectors to use wrappers

No problem, let me know when you're ready.

**Comment by averissimo** [comment]
The connectors have been updated, is this still blocked?

**Comment by gogonzo** [comment]
@chlebowa please proceed. Please bear in mind that we will have to present connectors to snowflake team and they will be put in the situation where they don't have any alternative but use a custom-connection-function (connection opener + module).

**Pull request merged**
