### PR TITLE
library calls possible within a call

### PR DESCRIPTION
**Pull request by gogonzo**
Possible to include `library` call in `eval_code`

https://github.com/insightsengineering/teal.code/issues/93

### CODE REVIEW

**Comment by chlebowa** [comment]
What if someone detaches a package that si in the middle of the search path (for whatever reason)?

**Comment by gogonzo** [comment]
> What if someone detaches a package that si in the middle of the search path (for whatever reason)?

as far as one uses `eval_code` to do so it's okey from reproducibility perspective

**Comment by chlebowa** [comment]
But you can then lose a function from scope and the condition won't be triggered. I can't decide if that's going to be a problem :thinking:

**Comment by gogonzo** [comment]
> But you can then lose a function from scope and the condition won't be triggered. I can't decide if that's going to be a problem 🤔

Removing namespace and then trying to obtain object from this namespace is a bug introduced by user. In the interactive session this would fail as well. It doesn't seem to be a `qenv` problem.

**Comment by chlebowa** [comment]
Sounds good :+1:

**Review by chlebowa — APPROVED** [review]

**Comment by chlebowa** [comment]
We haven't considered that using this feature forces us to call `teal.data` (in practice probably `teal`) before packages required for pre-processing.
Instead of 
```
  library(scda)
  library(scda.2022)
  library(dplyr)
  library(teal.modules.clinical)
  library(teal.modules.general)
  library(teal.osprey)
  library(nestcolor)
  # optional libraries
  library(sparkline)
```
one would do 
```
  library(teal)
  library(scda)
  library(scda.2022)
  library(dplyr)
  library(teal.modules.clinical)
  library(teal.modules.general)
  library(teal.osprey)
  library(nestcolor)
  # optional libraries
  library(sparkline)
```

This leaves us with a different search path:
```
                             old                           new
1                     .GlobalEnv                    .GlobalEnv
2              package:sparkline             package:sparkline
3              package:nestcolor             package:nestcolor
4            package:teal.osprey           package:teal.osprey
5                 package:osprey                package:osprey
6   package:teal.modules.general  package:teal.modules.general
7              package:shinyTree             package:shinyTree
8               package:ggmosaic              package:ggmosaic
9                package:ggplot2               package:ggplot2
10 package:teal.modules.clinical package:teal.modules.clinical
11                  package:tern                  package:tern
12               package:rtables               package:rtables
13            package:formatters            package:formatters
14                  package:teal                 package:dplyr
15        package:teal.transform             package:scda.2022
16              package:magrittr                  package:scda
17            package:teal.slice                  package:teal
18             package:teal.data        package:teal.transform
19                 package:shiny              package:magrittr
20                 package:dplyr            package:teal.slice
21             package:scda.2022             package:teal.data
22                  package:scda                 package:shiny
23                 tools:rstudio                 tools:rstudio
24                 package:stats                 package:stats
25              package:graphics              package:graphics
26             package:grDevices             package:grDevices
27                 package:utils                 package:utils
28              package:datasets              package:datasets
29               package:methods               package:methods
30                     Autoloads                     Autoloads
31                  package:base                  package:base
```

I don't think this should be a problem but it is something we should be aware of.

**Pull request merged**
