### PR TITLE
Introduce teal_data class

### PR DESCRIPTION
**Pull request by gogonzo**
Couple of fixes needed to use qenv in other packages:

Skärmavbild 2023-10-06 kl  10 43 48

https://cran.r-project.org/doc/manuals/R-exts.html#Namespaces-with-S4-classes-and-methods

### CODE REVIEW

**Comment by pawelru** [comment]
Please add NEWS

**Review by vedhav — APPROVED** [review]
LGTM

**Comment by chlebowa** [comment]
`methods::new` is no longer needed then, is it?

**Comment by gogonzo** [comment]
> methods::new is no longer needed then, is it?
True. Not needed, but not suggested to do otherwise neither

**Pull request merged**
