### PR TITLE
CRAN Release [skip vbump]

### PR DESCRIPTION
**Pull request by donyunardi**
Related to #132 
Pushing to CRAN

* Up-version the package (0.4.1) + update PR title to skip vbump.
* Built this locally and submit to CRAN
* git tag v0.4.1-rc# and push
* Address any CRAN feedback and repeat steps 2 and 3 until CRAN approves.
* Once in CRAN, then we will merge this to main and tag v0.4.1 for GH release

### CODE REVIEW

**Comment by donyunardi** [comment]
Submitted to CRAN
image

Tag created and pushed for v0.4.1-rc1

**Comment by m7pr** [comment]
Just re-submitted to CRAN. We need to accept the submission link that was sent to the maintainer

**Comment by averissimo** [comment]
I saw that the installation instructions were modified in #142

@m7pr did you consider removing the `insightsengineering` repo now that the package will live on CRAN?

```diff
diff --git a/README.md b/README.md
index 9bde0a9..79997cd 100644
--- a/README.md
+++ b/README.md
@@ -38,10 +38,11 @@ include:
 
 ## Installation
 
-From July 2023 `insightsengineering` packages are available on [r-universe](https://r-universe.dev/).
-
 ```r
 # stable versions
+install.packages('teal.code')
+
+# From September 2023 `insightsengineering` packages are available on [r-universe](https://r-universe.dev/).
 install.packages('teal.code', repos = c('https://insightsengineering.r-universe.dev', 'https://cloud.r-project.org'))
 
 # install.packages("pak")
```

**Comment by m7pr** [comment]
@averissimo this makes sense, for packages submitted to CRAN I will update that. For packages not released yet, I will follow isntructions from https://github.com/insightsengineering/coredev-tasks/issues/462 and basically follow https://github.com/insightsengineering/teal/pull/890

**Comment by m7pr** [comment]
@donyunardi any news on the resubmission feedback?

**Comment by m7pr** [comment]
Oh, I see it's released on CRAN ! https://cran.r-project.org/web/packages/teal.code/index.html

**Comment by m7pr** [comment]
@donyunardi would you mind merging and tagging this one?

**Review by m7pr — APPROVED** [review]

**Pull request merged**
