### PR TITLE
error handling for quosures

### LINKED ISSUE #59: [BUG] failing eval_code breaks the shiny app
When eval_code fails quosure is not returned anymore. It means that reactive which fails return error and breaks the whole app. What we actually need is to still return the quosure and keep the error messages (and warnings) per code element to print the proper diagnostics. 
If we decide to drop diagnostics feature some tryCatch is still needed, because reactives still should return quosure and instead of error message we would like to use `validate(q3)` in shiny apps.

```r
q1 <- new_quosure()
q2 <- eval_code(q1, iris2 <- iris)

q3 <- eval_code(q2, stop("elo"))
q3[["iris2"]]
```

```r
r1 <- reactive(new_quosure())
r2 <- reactive(eval_code(r1(), iris2 <- iris))

r3 <- reactive(r2(), stop("elo"))

get_code(r3()) # get_code fails as r3 doesn't return quosure anymore

```

Final acceptance criteria not yet formulated

### LINKED ISSUE #60: [Bug]: Methods doesn't work with shiny validation error
### What happened?

this problem can be simplified by:
```r
r1 <- <reactive  which returns quosure is returning validation error>

r2 <- reactive({
  eval_code(r1(), <code>)
})
```

`eval_code` gets `r1()` which is not a quosure but shiny-validation-error. eval_code doesn't know how to handle object of that class so it returns the error. 

We need to find the way to avoid this. For example see teal.goshawk::scatterplot and add any filter to exclude all observations:

```r

library(scda)

arm_mapping <- list(
  "A: Drug X" = "150mg QD",
  "B: Placebo" = "Placebo",
  "C: Combination" = "Combination"
)


ADSL <- synthetic_cdisc_data("latest")$adsl
ADLB <- synthetic_cdisc_data("latest")$adlb
var_labels <- lapply(ADLB, function(x) attributes(x)$label)
ADLB <- ADLB %>%
  dplyr::mutate(
    AVISITCD = dplyr::case_when(
      AVISIT == "SCREENING" ~ "SCR",
      AVISIT == "BASELINE" ~ "BL",
      grepl("WEEK", AVISIT) ~ paste("W", stringr::str_extract(AVISIT, "(?<=(WEEK ))[0-9]+")),
      TRUE ~ as.character(NA)
    ),
    AVISITCDN = dplyr::case_when(
      AVISITCD == "SCR" ~ -2,
      AVISITCD == "BL" ~ 0,
      grepl("W", AVISITCD) ~ as.numeric(gsub("[^0-9]*", "", AVISITCD)),
      TRUE ~ as.numeric(NA)
    ),
    AVISITCD = factor(AVISITCD) %>% stats::reorder(AVISITCDN),
    TRTORD = dplyr::case_when(
      ARMCD == "ARM C" ~ 1,
      ARMCD == "ARM B" ~ 2,
      ARMCD == "ARM A" ~ 3
    ),
    ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))]),
    ARM = factor(ARM) %>% stats::reorder(TRTORD),
    ACTARM = as.character(arm_mapping[match(ACTARM, names(arm_mapping))]),
    ACTARM = factor(ACTARM) %>% stats::reorder(TRTORD)
  )
attr(ADLB[["ARM"]], "label") <- var_labels[["ARM"]]
attr(ADLB[["ACTARM"]], "label") <- var_labels[["ACTARM"]]
#'
app <- init(
  data = cdisc_data(
    adsl <- cdisc_dataset("ADSL", ADSL, code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"),
    cdisc_dataset(
      "ADLB",
      ADLB,
      code = "ADLB <- synthetic_cdisc_data(\"latest\")$adlb
              var_labels <- lapply(ADLB, function(x) attributes(x)$label)
              ADLB <- ADLB %>%
                dplyr::mutate(AVISITCD = dplyr::case_when(
                    AVISIT == 'SCREENING' ~ 'SCR',
                    AVISIT == 'BASELINE' ~ 'BL',
                    grepl('WEEK', AVISIT) ~
                      paste('W', stringr::str_extract(AVISIT, '(?<=(WEEK ))[0-9]+')),
                    TRUE ~ as.character(NA)),
                  AVISITCDN = dplyr::case_when(
                    AVISITCD == 'SCR' ~ -2,
                    AVISITCD == 'BL' ~ 0,
                    grepl('W', AVISITCD) ~ as.numeric(gsub('[^0-9]*', '', AVISITCD)),
                    TRUE ~ as.numeric(NA)),
                  AVISITCD = factor(AVISITCD) %>% reorder(AVISITCDN),
                  TRTORD = dplyr::case_when(
                    ARMCD == 'ARM C' ~ 1,
                    ARMCD == 'ARM B' ~ 2,
                    ARMCD == 'ARM A' ~ 3),
                  ARM = as.character(arm_mapping[match(ARM, names(arm_mapping))]),
                  ARM = factor(ARM) %>% reorder(TRTORD),
                  ACTARM = as.character(arm_mapping[match(ACTARM, names(arm_mapping))]),
                  ACTARM = factor(ACTARM) %>% reorder(TRTORD))
               attr(ADLB[['ARM']], 'label') <- var_labels[['ARM']]
               attr(ADLB[['ACTARM']], 'label') <- var_labels[['ACTARM']]",
      vars = list(ADSL = adsl, arm_mapping = arm_mapping)
    ),
    check = TRUE
  ),
  modules = modules(
    tm_g_gh_scatterplot(
      label = "Scatter Plot",
      dataname = "ADLB",
      param_var = "PARAMCD",
      param = choices_selected(c("ALT", "CRP", "IGA"), "ALT"),
      xaxis_var = choices_selected(c("AVAL", "BASE", "CHG", "PCHG"), "BASE"),
      yaxis_var = choices_selected(c("AVAL", "BASE", "CHG", "PCHG"), "AVAL"),
      trt_group = choices_selected(c("ARM", "ACTARM"), "ARM"),
      color_manual = c(
        "150mg QD" = "#000000",
        "Placebo" = "#3498DB",
        "Combination" = "#E74C3C"
      ),
      shape_manual = c("N" = 1, "Y" = 2, "NA" = 0),
      plot_height = c(500, 200, 2000),
      facet_ncol = 2,
      trt_facet = FALSE,
      reg_line = FALSE,
      font_size = c(12, 8, 20),
      dot_size = c(1, 1, 12),
      reg_text_size = c(3, 3, 10)
    )
  )
)

shinyApp(app$ui, app$server)
```
image

--------------------------------

### sessionInfo()

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by nikolas-burkoff**
This will eventually close #59 and also close #60 it does not address #63 though

image

This is work in progress - I was having all sorts of problems with S3 and S4 classes and this is the best I can get so far - I'm especially proud of getting `req` working
Please let me know your thoughts even at this stage

Still to do:

- tests and documentation
- See [this](https://github.com/insightsengineering/teal.code/pull/61#issuecomment-1239183055) comment 

Test with the following - I will update as I update the PR

```
library(shiny)
library(teal.code)
library(magrittr)


ui <- fluidPage(
  fluidRow(
    column(6, h1("Code")),
    column(6, h1("Output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q1_code")),
    column(6, verbatimTextOutput("q1_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q2_code")),
    column(6, verbatimTextOutput("q2_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q3_code")),
    column(6, verbatimTextOutput("q3_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q4_code")),
    column(6, verbatimTextOutput("q4_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q5_code")),
    column(6, verbatimTextOutput("q5_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q6_code")),
    column(6, verbatimTextOutput("q6_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q7_code")),
    column(6, verbatimTextOutput("q7_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q8_code")),
    column(6, verbatimTextOutput("q8_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q9_code")),
    column(6, verbatimTextOutput("q9_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q10_code")),
    column(6, verbatimTextOutput("q10_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q11_code")),
    column(6, verbatimTextOutput("q11_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q12_code")),
    column(6, verbatimTextOutput("q12_output"))
  ),
  fluidRow(
    column(6, verbatimTextOutput("q13_code")),
    column(6, verbatimTextOutput("q13_output"))
  )
)

server <- function(input, output, session) {
  q1 <- reactive({
    new_quosure() %>%
    eval_code(code = 'stop("Error message details")')
  })

  output$q1_code <- reactive(
    'q1 <- reactive(new_quosure() %>%
      eval_code(stop("Error message details")))'
  )

  output$q1_output <- renderPrint(q1())

  q2 <- reactive({
    new_quosure() %>%
      eval_code(code = "x <- 0")
  })


  output$q2_code <- reactive(
    'q2 <- reactive(new_quosure() %>%
      eval_code("x <- 0")'
  )

  output$q2_output <- renderPrint(q2())

  q3 <- reactive({
    validate(need(q1(), "q1 is not valid"))
    "hello"
  })

  output$q3_code <- reactive(
    'q3 <- reactive({
    validate(need(q1(), "q1 is not valid"))
    "hello"
    })'
  )

  output$q3_output <- renderPrint(q3())

  q4 <- reactive({
    validate(need(q2(), "q2 is not valid"))
    "hello"
  })


  output$q4_code <- reactive(
    'q4 <- reactive({
     validate(need(q2(), "q2 is not valid"))
    "hello"
    })'
  )

  output$q4_output <- renderPrint(q4())

  q5 <- reactive({
    q1()[["x"]]
  })

  # Note case q2()[["not_valid"]] handled by teal.code issue #57

  output$q5_code <- reactive(
    'q5 <- reactive(q1()[["x"]])'
  )

  output$q5_output <- renderPrint({
    q5()
  })


  q6 <- reactive({
    eval_code(q2(), "w <- y * x")
  })


  output$q6_code <- reactive(
    'q6 <- reactive(eval_code(q2(), "w <- y * x"))'
  )

  output$q6_output <- renderPrint(q6())

  q7 <- reactive({
    eval_code(q1(), "w <- 10")
  })


  output$q7_code <- reactive(
    'q7 <- reactive(eval_code(q1(), "w <- 10")'
  )

  output$q7_output <- renderPrint(q7())

  q8 <- reactive({
    req(q1())
    "hello"
  })


  output$q8_code <- reactive(
    'q8 <- reactive({
      req(q1())
      "hello"
    })'
  )

  output$q8_output <- renderPrint(q8())


  q9 <- reactive({
    join(q2(), q7()) %>% get_var("x")
  })


  output$q9_code <- reactive(
    'q9 <- reactive({
      join(q2(), q7()) %>% get_var("x")
    })'
  )

  output$q9_output <- renderPrint(q9())

  q10 <- reactive({
    join(q2(), q7()) %>% get_code()
  })


  output$q10_code <- reactive(
    'q10 <- reactive({
      join(q2(), q7()) %>% get_code()
    })'
  )

  output$q10_output <- renderPrint(q10())


  q11 <- reactive({
    new_quosure() %>%
      eval_code("x <- 0") %>%
      eval_code("y <- 0") %>%
      eval_code("w <- u * x") %>%
      eval_code("v <- x") %>%
      get_code()
  })


  output$q11_code <- reactive(
    'q11 <- reactive({
      new_quosure() %>%
      eval_code("x <- 0") %>%
      eval_code("y <- 0") %>%
      eval_code("w <- u * x") %>%
      eval_code("v <- x") %>%
      get_code()
    })'
  )

  output$q11_output <- renderPrint(q11())


  q12_a <- reactive({
    validate(need(1 > 4, "Error: 1 is less than 4"))
    new_quosure() %>% eval_code("x <- 1")
  })

  q12_b <- reactive({
    get_code(q12_a())
  })

  output$q12_code <- reactive(
    'q12_a <- reactive({
      validate(need(1 > 4, "Error: 1 is less than 4"))
      new_quosure() %>% eval_code("x <- 1")
    })

    q12_b <- reactive({
      get_code(q12_a())
    })
    '
  )

  output$q12_output <- renderPrint(q12_b())

  q13a <- reactive(stop("error in the reactive"))
  q13b <- reactive({
    req(q13a())
    "hello"
  })
  output$q13_code <- reactive(
    'q13a <- reactive(stop("error in the reactive"))
    q13b <- reactive({
      req(q13a())
      "hello"
    })
    '
  )
  output$q13_output <- renderPrint(q13b())
}

runApp(shinyApp(ui, server))
```

### CODE REVIEW

**Comment by donyunardi** [comment]
Thanks for working on this @nikolas-burkoff 
This looks great and very promising.

Only one question from me, since we don't know when the error will occur, does this mean we always have to wrap the `Quosure` object with `capture.output()` in teal modules?

**Comment by nikolas-burkoff** [comment]
> Only one question from me, since we don't know when the error will occur, does this mean we always have to wrap the Quosure object with capture.output() in teal modules?

No, only if you want to actually print the quosure object itself - in modules you never want to do that only extract variables/get code - but in this example I wanted to show all sorts of cases

**Comment by nikolas-burkoff** [comment]
So this does not yet handle the following:
```
output_q <- reactive( 
  req(FALSE)
  new_quosure() %>% eval_code("x <- 1")
)
...
card$append_src(paste(teal.code::get_code(output_q()), collapse = "\n"))
...
teal.widgets::verbatim_popup_srv(
      id = "rcode",
      verbatim_content = reactive(teal.code::get_code(output_q())),
      title = label
)
```

This case, which we see a lot, is more painful

**Review by gogonzo — COMMENTED** [review]
I like of idea of having QuosureError and passing it down the reactive chain. But I think it's not needed, we can still return error from the `eval_code` and this error can travel down.

**Comment by nikolas-burkoff** [comment]
Closed preferring https://github.com/insightsengineering/teal.code/pull/65

**Pull request closed without merging**
